version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.76.0

    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

references:
  Exchange:
    context: Exchange
